substitutions:
  name: esphome-test
  device_id: esphome-test-01
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

packages:
  board: !include ./esp32-s3-devkitc.yaml
  common: !include ./common.yaml

esphome:
  name: ${name}
  comment: "test firmware"
  project:
    name: test.esphome-test
    version: "0.1.0"
